services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: tkgh001_database
      DATABASE_USER: tkgh001_user
      DATABASE_PASSWORD: tkgh001_password

  database:
    image: mariadb
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    environment:
      MARIADB_DATABASE: tkgh001_database
      MARIADB_USER: tkgh001_user
      MARIADB_PASSWORD: tkgh001_password
      MARIADB_ROOT_PASSWORD: tkgh001_root_password

volumes:
  database:
